#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := project_template

IDF_PATH=/home/xan/esp/ESP8266_RTOS_SDK

include $(IDF_PATH)/make/project.mk

